#!/bin/bash
# Original version
#https://github.com/KabbAmine/myDotFiles/tree/master/i3/blocklets

declare -A state_icons=( \
	["clear"]="☀️" \
	["cloud"]="☁️" \
	["fog"]="🌧️" \
	["generic"]="☀️" \
	["rain"]="🌧️" \
	["showers"]="🌧️" \
	["sleet"]="🌧️" \
	["snow"]="🌨️" \
	["sun"]="☀️" \
	["thunder"]="⛈️" \
)

getCurrWeather() {
	local datas=$(curl --silent "wttr.in/" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g")
	echo "$datas"
}

parseDatas() {
	local head=$(echo "$1" | head -n 7)
	local state=$(echo "$head" | head -n 3 | tail -n 1 | sed -e 's=.*\([A-Z].*\)=\1=')
	local temperature=$(echo "$head" | grep -o "[-0-9]*\ *°C")

	echo "${state} ${temperature}"
}

datas=$(getCurrWeather)

# Quit if no datas were found
check=$(echo "$datas" | grep 'Not Found')
if [ -n "$check" ]; then exit; fi

w=$(parseDatas "$datas")

yad="yad --text-info --no-buttons --on-top --center --skip-taskbar --width 1015 --height 620"
case $BLOCK_BUTTON in
	1) curl --silent "wttr.in/${city}" | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" | $yad;;     # left click
	2) pkill -RTMIN+2 i3blocks;;    # middle click
esac

state=$(echo "$w" | sed -e 's=\(.*\)[0-9]+=\1=')
temp=$(echo "$w" | awk '{print $(NF-1) $NF}')

# Ignore case
shopt -s nocasematch

# Get the appropriate icon glyph
icon=${state_icons["generic"]}
for s in ${!state_icons[*]}; do
	if [[ $state =~ $s ]]; then
		icon=${state_icons[$s]}
		break
	fi
done

echo "$icon $temp"
echo
